### ISSUE TITLE
请问你这份代码提交之后成绩如何？

### ISSUE THREAD

**Issue by AliceAria** [1246299550li/huawei#1]
我本地测试了你这份代码，100w的环会报错。
然后我借鉴了你代码里输出的部分，提交之后runtime error了。在改输出函数之前，我是有成绩的。请问你知道怎么回事么？

**Comment by papiers** [comment]
100w的环没问题呀 我的输出部分写的不好 正在改

**Comment by AliceAria** [comment]
抱歉。
不好意思啦，我刚又跑了一下100w的环，的确是没问题的，可能是我昨天哪儿弄错了。
至于输出，我本来用的printf，改成你的fwite之后，一看变快了很多，很开心的提交了，显示re，刚我重新检查了一下，改代码的时候不小心又bug，漏写了好多数据，现在改好之后，发现fwite的速度和printf差不太多，只是略微快了一点点。
抱歉啦

**Comment by risingstar-zr** [comment]
老哥，cpp代码写点注释不香吗
